apiVersion: v1
kind: Pod
metadata:
  name: pod-using-secrets
spec:
  containers:
    - name: container-using-secrets
      image: ubuntu
      env:
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: test-secret
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: test-secret
              key:  database-password

